import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import { useAuth } from '../components/AuthContext';
import { Typography } from '@mui/material';


export default function Home() {
  const { currentUser, userData } = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="button" className={styles.title}>
          {!!userData?.userName ? `Welcome back, ${userData?.userName}!` : "Welcome!"}
        </Typography>
        </main>

      <footer className={styles.footer}>
          Powered by hopes and dreams.
      </footer>
    </div>
  )
}

